spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ddd_demo?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接检测配置
      validation-query: SELECT 1
      test-while-idle: true
      # 监控配置
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456

# Swagger 配置
springdoc:
  swagger-ui:
    enabled: true
knife4j:
  enable: true

