spring:
  datasource:
    url: jdbc:mysql://prod-server:3306/ddd_demo?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      # 连接池配置
      initial-size: 20
      min-idle: 20
      max-active: 50
      # 连接检测配置
      validation-query: SELECT 1
      test-while-idle: true
      # 监控配置
      stat-view-servlet:
        enabled: true
        allow: 10.0.0.0/16,192.168.0.0/16
        login-username: ${DRUID_USERNAME:admin}
        login-password: ${DRUID_PASSWORD:prod123}
      # SQL防火墙配置
      filter:
        wall:
          enabled: true

# Swagger 配置
springdoc:
  swagger-ui:
    enabled: false
knife4j:
  enable: false

# 生产环境禁用MyBatis Plus SQL日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl 