spring:
  profiles:
    active: dev
  application:
    name: ddd-demo
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    
server:
  port: 8080
  servlet:
    context-path: /api

# MyBatis Plus配置
mybatis-plus:
   mapper-locations: classpath:mapper/*.xml
   type-aliases-package: com.example.domain.entity
   configuration:
    map-underscore-to-camel-case: true


# Knife4j配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
knife4j:
  enable: true



